---
name: preview
on: [pull_request]
jobs:
  preview:
    name: Publish preview
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Set up Expo
        uses: expo/expo-github-action@v5
        with:
          expo-cache: true
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Publish to Expo
        uses: expo/expo-preview-action@@lukmccall/add-new-build-is-requier-warning
        with:
          channel: pr-${{ github.event.number }}
        id: publish
      - name: Comment deployment link
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: >
            Awesome! You can [preview the PR here](${{ steps.publish.outputs.EXPO_QR_CODE_URL }}).
            <br/><a href="${{ steps.publish.outputs.EXPO_QR_CODE_URL }}"><img src="${{ steps.publish.outputs.EXPO_QR_CODE_URL }}" height="512px" width="512px"></a>
            ${{ steps.publish.outputs.EXPO_NEW_BUILD_IS_REQUIRED_MESSAGE }}
