---
name: preview
on: [pull_request]
jobs:
  preview:
    name: Publish preview
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Set up Expo
        uses: expo/expo-github-action@v5
        with:
          expo-cache: true
          expo-version: 4.x
          expo-token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Publish to Expo
        uses: ./expo-preview-action
        with:
          channel: pr-${{ github.event.number }}
      - name: Echo
        run: echo "cos"
